# Generated by Django 4.2.5 on 2025-06-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='suplier',
            new_name='supplier',
        ),
    ]
